[2025-05-17T00:00:00.980+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_to_duckdb.run_etl_script scheduled__2025-05-16T23:00:00+00:00 [queued]>
[2025-05-17T00:00:00.982+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_to_duckdb.run_etl_script scheduled__2025-05-16T23:00:00+00:00 [queued]>
[2025-05-17T00:00:00.982+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-05-17T00:00:00.987+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): run_etl_script> on 2025-05-16 23:00:00+00:00
[2025-05-17T00:00:00.988+0000] {standard_task_runner.py:60} INFO - Started process 442 to run task
[2025-05-17T00:00:00.990+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgres_to_duckdb', 'run_etl_script', 'scheduled__2025-05-16T23:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_postgres_to_duckdb.py', '--cfg-path', '/tmp/tmp3wcfdjvm']
[2025-05-17T00:00:00.991+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask run_etl_script
[2025-05-17T00:00:00.997+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-17T00:00:01.010+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_postgres_to_duckdb.run_etl_script scheduled__2025-05-16T23:00:00+00:00 [running]> on host 5f495f717811
[2025-05-17T00:00:01.036+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_postgres_to_duckdb' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-16T23:00:00+00:00'
[2025-05-17T00:00:01.037+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-17T00:00:01.037+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/etl/etl_postgres_to_duckdb.py']
[2025-05-17T00:00:01.040+0000] {subprocess.py:86} INFO - Output:
[2025-05-17T00:00:01.069+0000] {subprocess.py:93} INFO - Extracting data from Postgres...
[2025-05-17T00:00:01.069+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-17T00:00:01.069+0000] {subprocess.py:93} INFO -   File "/opt/airflow/etl/etl_postgres_to_duckdb.py", line 47, in <module>
[2025-05-17T00:00:01.072+0000] {subprocess.py:93} INFO -     data = extract_from_postgres()
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO -   File "/opt/airflow/etl/etl_postgres_to_duckdb.py", line 16, in extract_from_postgres
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO -     conn = psycopg2.connect(
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-05-17T00:00:01.073+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-05-17T00:00:01.074+0000] {subprocess.py:93} INFO - 
[2025-05-17T00:00:01.074+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-17T00:00:01.078+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-17T00:00:01.079+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_postgres_to_duckdb, task_id=run_etl_script, execution_date=20250516T230000, start_date=20250517T000000, end_date=20250517T000001
[2025-05-17T00:00:01.083+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task run_etl_script (Bash command failed. The command returned a non-zero exit code 1.; 442)
[2025-05-17T00:00:01.088+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-17T00:00:01.094+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-17T00:24:52.802+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_to_duckdb.run_etl_script scheduled__2025-05-16T23:00:00+00:00 [queued]>
[2025-05-17T00:24:52.806+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_to_duckdb.run_etl_script scheduled__2025-05-16T23:00:00+00:00 [queued]>
[2025-05-17T00:24:52.806+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-05-17T00:24:52.811+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): run_etl_script> on 2025-05-16 23:00:00+00:00
[2025-05-17T00:24:52.813+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2025-05-17T00:24:52.815+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgres_to_duckdb', 'run_etl_script', 'scheduled__2025-05-16T23:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_postgres_to_duckdb.py', '--cfg-path', '/tmp/tmpxqup1955']
[2025-05-17T00:24:52.817+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask run_etl_script
[2025-05-17T00:24:52.825+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-17T00:24:52.840+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_postgres_to_duckdb.run_etl_script scheduled__2025-05-16T23:00:00+00:00 [running]> on host d4675334c61f
[2025-05-17T00:24:52.876+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_postgres_to_duckdb' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-16T23:00:00+00:00'
[2025-05-17T00:24:52.877+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-17T00:24:52.877+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/etl/etl_postgres_to_duckdb.py']
[2025-05-17T00:24:52.880+0000] {subprocess.py:86} INFO - Output:
[2025-05-17T00:24:53.575+0000] {subprocess.py:93} INFO - Extracting data from Postgres...
[2025-05-17T00:24:53.576+0000] {subprocess.py:93} INFO - Fetched 62 rows.
[2025-05-17T00:24:53.576+0000] {subprocess.py:93} INFO - Loading data into DuckDB...
[2025-05-17T00:24:53.576+0000] {subprocess.py:93} INFO - Done!
[2025-05-17T00:24:53.613+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-17T00:24:53.624+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_postgres_to_duckdb, task_id=run_etl_script, execution_date=20250516T230000, start_date=20250517T002452, end_date=20250517T002453
[2025-05-17T00:24:53.654+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-17T00:24:53.661+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
